# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languageDirection = "ltr"
contentDir = "content/en"
title = "AkiHitori's blog"
weight = 2

[en.params]
sidebar.subtitle = "Posting random stuff"
article.license.default = "Licensed under CC BY-NC-SA 4.0"

[zh-cn]
languageName = "简体中文"
languageDirection = "ltr"
contentDir = "content/zh-cn"
title = "AkiHitori的博客"
weight = 1

[zh-cn.params]
sidebar.subtitle = "还不知道写什么"
article.license.default = "使用 CC BY-NC-SA 4.0 协议"

[ja]
languageName = "日本语"
languageDirection = "ltr"
contentDir = "content/ja"
title = "AkiHitoriのブログ"
weight = "3"

[ja.params]
sidebar.subtitle = "まだ何を書くか決まっていない"
article.license.default = "CC BY-NC-SA 4.0 ライセンスを使用"